import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
// import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <nav>
            <ul>
              <li>
                <Link href="/">Trang chủ</Link>
              </li>
              <li>
                <Link href="/gioi-thieu">Giới thiệu</Link>
              </li>
              <li>
                <Link href="/lien-he">Liên hệ</Link>
              </li>
              <li>
                <Link href="/tin-tuc">Tin tức</Link>
              </li>
            </ul>
          </nav>
        </header>
        {children}
        <footer>Footer</footer>
      </body>
    </html>
  );
}
